### ISSUE TITLE
Contiv-VPP K8S deployment is creating issue in Non-Docker based container runtime environment

### ISSUE THREAD

**Issue by rajpratik71** [contiv/vpp#1767]
Currently trying Contiv-VPP K8S based deployment in air-gapped customized environment 

Some issue are :

-  **failed to list sandboxed pods**

`
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
*   FINALIZED EVENT: Database Resync (Remote DB)                                                                              #0 *
*   HANDLED BY: contivconf, nodesync, podmanager                                                                       took 13ms *
*   ERRORS:                                                                                                                      *
*       * podmanager: failed to list sandbox containers: cannot connect to Docker endpoint                                       *
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
time="2021-12-07 07:06:55.11511" level=info msg="Agent plugin state update." lastErr="failed to list sandbox containers: cannot connect to Docker endpoint" loc="statuscheck/plugin_impl_statuscheck.go(183)" logger=status-check plugin=controller state=error

`

-  **Unable to connect Docker endpoint**
`
time="2021-12-07 07:06:54.66932" level=debug msg="Using docker client endpoint: unix:///var/run/docker.sock" loc="descriptor/microservice.go(112)" logger=linux-nsplugin
time="2021-12-07 07:06:54.66936" level=info msg="Namespace plugin initialized" loc="nsplugin/ns_plugin.go(111)" logger=linux-nsplugin
time="2021-12-07 07:06:54.66940" level=debug msg="-> Init(): linux-ifplugin" loc="agent/agent.go(220)" logger=agent
time="2021-12-07 07:06:54.66950" level=debug msg="Linux IfPlugin config found" loc="ifplugin/ifplugin.go(166)" logger=linux-ifplugin
time="2021-12-07 07:06:54.66953" level=debug msg="Linux interface plugin config: &{Disabled:false GoRoutinesCnt:10}" loc="ifplugin/ifplugin.go(82)" logger=linux-ifplugin
time="2021-12-07 07:06:54.66966" level=debug msg="-> Init(): vpp-ifplugin" loc="agent/agent.go(220)" logger=agent
time="2021-12-07 07:06:54.66969" level=warning msg="Failed to list Docker containers: cannot connect to Docker endpoint" loc="descriptor/microservice.go(304)" logger=linux-nsplugin.ms-descriptor
time="2021-12-07 07:06:54.66974" level=debug msg="config  not found" loc="ifplugin/config.go(54)" logger=vpp-ifplugin
`

-  **Fail to run "stn-install" script required for Steal-The-NIC feature**  as it require docker to be installed on Node
`
https://raw.githubusercontent.com/contiv/vpp/master/k8s/stn-install.sh
`

Mainly I am looking for some help or guidance regarding these issue. Also, I want to know any specific base system preparation is required in terms of installing any specific library or dependencies.  

**Environment**:

- Container Orchestrator and version: containerd v1.3.9

- Cloud provider or hardware configuration: On-premise  Air-gapped Environment

- OS (e.g. from /etc/os-release): 

- K8S Version: v1.19.9 

`
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
`

- Kernel (e.g. `uname -a`):
`
 Linux xxx-worker-rgu00u.xxx 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by brunodzogovic** [comment]
You need to start the kubernetes cluster with the Docker daemon initialized with systemd as a cgroup driver. Or initiailze the cluster as: 
```
kind: ClusterConfiguration                  
apiVersion: kubeadm.k8s.io/v1beta3                
kubernetesVersion: {{ kube_version }}             
api:                                              
  advertiseAddress: {{ advertise_address }}       
  bindPort: {{ bind_port }}                       
---                                               
kind: KubeletConfiguration                        
apiVersion: kubelet.config.k8s.io/v1beta1         
cgroupDriver: systemd                             
networking:                                       
  podSubnet: {{ pod_subnet }}
```

Also note that this project is not maintained anymore. It's hard to get new things working, especially for a one-man job due to the complexity of the service structure
